// <auto-generated />
using System;
using FarmacorpPOS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmacorpPOS.Infrastructure.Migrations
{
    [DbContext(typeof(FarmacorpDbContext))]
    [Migration("20260613211821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmacorpPOS.Domain.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdCategoriaPadre")
                        .HasColumnType("int");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdCategoriaPadre");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.CodigoBarra", b =>
                {
                    b.Property<int>("IdCodigoBarra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCodigoBarra"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("UniqueCodigo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("IdCodigoBarra");

                    b.HasIndex("IdProducto");

                    b.HasIndex("UniqueCodigo")
                        .IsUnique();

                    b.ToTable("CodigosBarras", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.ErpProducto", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("UniqueCodigo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("IdProducto");

                    b.HasIndex("UniqueCodigo")
                        .IsUnique();

                    b.ToTable("ErpProductos", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.ExpProducto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipoProducto")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdTipoProducto");

                    b.ToTable("ExpProductos", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.ProductoCategoria", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductosCategorias", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.TipoProducto", b =>
                {
                    b.Property<int>("IdTipoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoProducto"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoProducto");

                    b.ToTable("TiposProducto", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.VentaExpress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UniqueProducto")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.ToTable("VentaExpress", (string)null);
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Categoria", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.Categoria", "CategoriaPadre")
                        .WithMany()
                        .HasForeignKey("IdCategoriaPadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.CodigoBarra", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.ErpProducto", "ErpProducto")
                        .WithMany("CodigosBarras")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ErpProducto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.ErpProducto", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.ExpProducto", "Producto")
                        .WithOne("ErpProducto")
                        .HasForeignKey("FarmacorpPOS.Domain.ErpProducto", "IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.ExpProducto", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.TipoProducto", "TipoProducto")
                        .WithMany("Productos")
                        .HasForeignKey("IdTipoProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.ProductoCategoria", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.Categoria", "Categoria")
                        .WithMany("ProductosCategorias")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FarmacorpPOS.Domain.ExpProducto", "Producto")
                        .WithMany("ProductosCategorias")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.VentaExpress", b =>
                {
                    b.HasOne("FarmacorpPOS.Domain.ExpProducto", "ExpProducto")
                        .WithMany("Ventas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpProducto");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.Categoria", b =>
                {
                    b.Navigation("ProductosCategorias");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.ErpProducto", b =>
                {
                    b.Navigation("CodigosBarras");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.ExpProducto", b =>
                {
                    b.Navigation("ErpProducto")
                        .IsRequired();

                    b.Navigation("ProductosCategorias");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("FarmacorpPOS.Domain.TipoProducto", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
